dependency trackinitial release (#4)
NethServer/dev#7477

diff --git a/imageroot/actions/restore-module/40restore_database b/imageroot/actions/restore-module/40restore_database
--- a/imageroot/actions/restore-module/40restore_database
+++ b/imageroot/actions/restore-module/40restore_database
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (C) 2022 Nethesis S.r.l.
+# Copyright (C) 2025 Nethesis S.r.l.
 # SPDX-License-Identifier: GPL-3.0-or-later
 #
 
@@ -17,8 +17,12 @@ docker_temp_server_stop
 exit $ec
 EOS
 
-# Override the image /docker-entrypoint-initdb.d contents, to restore the
-# DB dump file. The container will be stopped at the end
+# read secrets.env and set the variable POSTGRES_TOKEN
+POSTGRES_TOKEN=$(grep -E '^POSTGRES_TOKEN=' secrets.env | cut -d= -f2-)
+if [[ -z "$POSTGRES_TOKEN" ]]; then
+    echo "Cannot restore: POSTGRES_TOKEN is not set in secrets.env"
+    exit 1
+fi
 
 podman run \
     --rm \
@@ -28,7 +32,7 @@ podman run \
     --volume=postgres-data:/var/lib/postgresql/data:Z \
     --replace --name=restore_db \
     --env POSTGRES_USER=postgres \
-    --env POSTGRES_PASSWORD=Nethesis,1234 \
+    --env POSTGRES_PASSWORD=${POSTGRES_TOKEN} \
     --env POSTGRES_DB=dependencytrack \
     --env TZ=UTC \
     "${POSTGRES_IMAGE}" < dependencytrack.pg_dump
